spring:
   application:
       name: organization-service
   profiles:
       active: dev
   config:
       import: optional:configserver:http://localhost:8071

eureka:
   instance:
      preferIpAddress: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl: 
         defaultZone: http://localhost:8070/eureka/